export const stats = [
  {
    label: "Total Citizens",
    value: "4,829",
    icon: "group",
    detailIcon: "trending_up",
    detail: "+2.4% this year",
    detailClass: "text-secondary",
    hoverClass: "group-hover:text-blue-50",
  },
  {
    label: "New Borns (Q3)",
    value: "42",
    icon: "child_care",
    detailIcon: "child_care",
    detail: "Recorded in 2023",
    detailClass: "text-tertiary-container",
    hoverClass: "group-hover:text-amber-50",
  },
  {
    label: "Mortality Rate",
    value: "0.8%",
    icon: "analytics",
    detailIcon: "sentiment_dissatisfied",
    detail: "-0.2% improvement",
    detailClass: "text-error",
    hoverClass: "group-hover:text-red-50",
  },
];

export const residents = [
  {
    nik: "3273010405880003",
    name: "Aris Munandar",
    initials: "AM",
    avatarClass: "bg-blue-100 text-blue-900",
    dusun: "Krajan II",
    rtRw: "RT 04 / RW 02",
    status: "ACTIVE",
    statusClass: "bg-secondary-fixed text-on-secondary-fixed-variant",
  },
  {
    nik: "3273012110920001",
    name: "Siti Wahyuni",
    initials: "SW",
    avatarClass: "bg-slate-200 text-slate-600",
    dusun: "Mulyo Indah",
    rtRw: "RT 01 / RW 05",
    status: "MOVED",
    statusClass: "bg-surface-container-high text-on-surface-variant",
  },
  {
    nik: "3273011508550002",
    name: "Bambang Triatmojo",
    initials: "BT",
    avatarClass: "bg-amber-100 text-amber-900",
    dusun: "Krajan I",
    rtRw: "RT 02 / RW 01",
    status: "ACTIVE",
    statusClass: "bg-secondary-fixed text-on-secondary-fixed-variant",
  },
  {
    nik: "3273010902450007",
    name: "Rahmat Mulyadi",
    initials: "RM",
    avatarClass: "bg-red-100 text-red-900",
    dusun: "Dusun Rejo",
    rtRw: "RT 05 / RW 04",
    status: "DECEASED",
    statusClass: "bg-error-container text-on-error-container",
  },
];
